on:
  workflow_call:
    inputs:
      ship:
        description: 'Name of ship/GCP instance'
        type: string
        default: false
        required: true
    secrets:
      GCP_CREDENTIALS:
        required: true
      GCP_PROJECT:
        required: true
      GCP_USER:
        required: true
      GCP_ZONE:
        required: true
      TAILSCALE_AUTHKEY:
        required: true

jobs:
  upload:
    runs-on: 'ubuntu-latest'
    name: 'Deploy Hoon files to ship'

    steps:
      - uses: 'actions/checkout@v3'

      - id: 'tailscale'
        name: 'Login to Tailscale'
        uses: 'tailscale/github-action@v1'
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - id: 'gcp-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: 'deploy'
        name: 'SSH and sync desk'
        run: ./.github/scripts/deploy.sh ${{ inputs.ship }} ${{ github.ref_name }}
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
          GCP_ZONE: ${{ secrets.GCP_ZONE }}
          GCP_USER: ${{ secrets.GCP_USER }}
