name: Deploy Hoon / Production

on:
  push:
    branches:
      - master
    paths:
      - '.github/scripts/**.sh'
      - '.github/workflows/**.yml'
      - 'desk/**'

jobs:
  urbit:
    uses: ./.github/workflows/deploy.yml
    with:
      ship: 'litnec-dozzod-marzod'
      branch: 'master'
    secrets: inherit
