name: Deploy Hoon / Development

on:
  push:
    branches:
      - develop
    paths:
      - 'desk/**'

jobs:
  urbit:
    uses: ./.github/workflows/deploy.yml
    with:
      ship: 'samnec-dozzod-marzod'
    secrets: inherit
