name: Deploy Hoon / Production

on:
  push:
    branches:
      - master
    paths:
      - 'desk/**'

jobs:
  urbit:
    uses: ./.github/workflows/deploy.yml
    with:
      ship: 'litnec-dozzod-marzod'
    secrets: inherit
