name: Upload Glob / Development

on:
  push:
    branches:
      - develop
    paths:
      - 'ui/**'

jobs:
  urbit:
    uses: ./.github/workflows/glob.yml
    with:
      ship: 'samnec-dozzod-marzod'
      password: 'SHIP_PASSWORD_DEV'
      branch: 'develop'
      url: 'bait-dev.tlon.io'
    secrets: inherit
